#!/bin/bash

# set up the two monitors for bspwm
# NOTE This is a simplistic approach because I already know the settings I
# want to apply.

# feh --recursive --randomize --auto-zoom --geometry 2560x1440+1920+0  --slideshow-delay 5 -B black --action "gvfs-trash '%f'" ~/Pictures

# my_laptop_external_monitor=$(xrandr --query | grep 'DisplayPort-0')
# if [[ $my_laptop_external_monitor = *connected* ]]; then
#     xrandr --output HDMI-A-0 --mode 1920x1080 --rate 144.00 --rotate normal --output DisplayPort-0 --primary --mode 2560x1440 --rotate normal --right-of HDMI-A-0
# fi


xrandr --output HDMI-A-0 --mode 1920x1080 --rate 144.00 --rotate normal --output DisplayPort-0 --primary --mode 2560x1440 --rotate normal --right-of HDMI-A-0
