#!/bin/sh

#### AUTOSTART ####
sxhkd &
#picom &
#nitrogen --restore &
#./.config/bspwm/panel.sh &
/home/puggi/.config/bspwm/autostart &
# run the xrandr command if an external monitor is connected to the
# laptop.  This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.
if [ -x /home/puggi/.scripts/own_script_bspwm_laptop_dual_monitor ];then
    /home/puggi/.scripts/own_script_bspwm_laptop_dual_monitor &
fi
#### MONITORS ####
bspc monitor eDP -d 1 2 3 4 5 6 7 #6 7 8 9
bspc monitor DisplayPort-0 -d 8 9 10 11 12 13 14
#bspc monitor DisplayPort-1 -d 1 2 3 4 5 6 7 8 9
#bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9

/home/puggi/.scripts/wallpaper_handler.sh &
# i=1
# for monitor in $(bspc query -M); do
# bspc monitor $monitor \
#         -n "$i" \
#         -d $i/{a,b,c}#1 2 3 4 5 6 7 8 9
#     let i++
# done
#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  2
bspc config window_gap                    10
bspc config top_padding                   0 #20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               false
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    false
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config automatic_scheme              spiral

#### BSPWM coloring ####
bspc config normal_border_color		      "#FFCA28"
bspc config active_border_color	        "#FFE082"
bspc config focused_border_color	      "#FFA000"
bspc config presel_feedback_color	      "#FFA000"
bspc config urgent_border_color 	      "#EF5350"


/home/puggi/.config/polybar/launch.sh &

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bspc rule -a Nextcloud desktop='^7' state=floating
bspc rule -a Zathura state=tiled
bspc rule -a System-config-printer.py state=floating
bspc rule -a Emacs state=tiled
